#!/usr/bin/env python3
"""Backend narrator for the split-screen demo recording.

Two modes, meant for two stacked terminal panes beside the chat UI:

  python3 scripts/demo_tap.py agent   # top: request -> tools/list -> plan -> steps -> answer
  python3 scripts/demo_tap.py audit   # bottom: MCP audit stream (every tools/call)

Reads only public/real surfaces — docker compose logs, the MCP tools/list
method, GET /v1/jobs/{id} — so everything on screen is genuine enforcement,
not staging. Stdlib only; run on the host from the repo root after
`make up && make seed && make tokens`.
"""
import json
import subprocess
import sys
import time
import urllib.request

API = "http://localhost:8000"
MCP = "http://localhost:8001"
TOKENS_PATH = "services/frontend/public/tokens.json"

BOLD, DIM, RESET = "\033[1m", "\033[2m", "\033[0m"
CYAN, YELLOW, GREEN, RED, MAGENTA = (
    "\033[36m", "\033[33m", "\033[32m", "\033[31m", "\033[35m")

OUTCOME_COLOR = {"ok": GREEN, "not_authorized": RED,
                 "upstream_unavailable": YELLOW, "not_found": YELLOW,
                 "invalid_args": YELLOW}
STEP_COLOR = {"running": DIM, "repairing": YELLOW,
              "complete": GREEN, "failed": RED}
STEP_GLYPH = {"pending": "○", "running": "⟳", "repairing": "⟲",
              "complete": "✓", "failed": "✗"}


def say(text=""):
    print(text, flush=True)


def http_json(url, token, payload=None):
    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode() if payload is not None else None,
        headers={"Authorization": f"Bearer {token}",
                 "Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=5) as resp:
        return json.loads(resp.read())


def tools_list(token):
    body = http_json(f"{MCP}/mcp", token, {
        "jsonrpc": "2.0", "id": 1, "method": "tools/list", "params": {}})
    return sorted(t["name"] for t in body["result"]["tools"])


def load_tokens():
    try:
        with open(TOKENS_PATH) as f:
            return json.load(f)
    except FileNotFoundError:
        sys.exit(f"{TOKENS_PATH} not found — run `make tokens` first")


def tail(*services):
    """Yield parsed JSON log records from `docker compose logs -f`."""
    proc = subprocess.Popen(
        ["docker", "compose", "logs", "-f", "--no-color", "--no-log-prefix",
         "--since", "1s", *services],
        stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True)
    for line in proc.stdout:
        line = line.strip()
        if not line.startswith("{"):
            continue
        try:
            yield json.loads(line)
        except json.JSONDecodeError:
            continue


def compact(obj, limit=110):
    text = json.dumps(obj, separators=(",", ":"))
    return text if len(text) <= limit else text[:limit] + "…"


# --- agent mode -----------------------------------------------------------------


def banner_roles(tokens):
    say(f"{BOLD}{MAGENTA}══ AGENT / JOB VIEW ═════════════════════════════════{RESET}")
    say(f"{DIM}per-user tool visibility (MCP tools/list, filtered server-side):{RESET}")
    for user in sorted(tokens):
        names = tools_list(tokens[user])
        wdp = [n for n in names if "wdp" in n]
        note = "" if wdp else f"  {YELLOW}(WDP tools withheld — no wdp_reader role){RESET}"
        say(f"  {BOLD}{user}{RESET}: {len(names)} tools{note}")
        say(f"    {DIM}{', '.join(names)}{RESET}")
    say()


def watch_job(job_id, token):
    seen_plan = False
    step_status = {}
    while True:
        try:
            job = http_json(f"{API}/v1/jobs/{job_id}", token)
        except Exception:
            time.sleep(0.4)
            continue
        if not seen_plan and job.get("plan"):
            plan = job["plan"]
            say(f"  {YELLOW}{BOLD}PLAN generated by LLM, validated against contract:{RESET}")
            say(f"  {YELLOW}intent:{RESET} {plan.get('intent', '')}")
            for step in plan.get("steps", []):
                say(f"    {step['id']}. {BOLD}{step['tool']}{RESET} "
                    f"{DIM}{compact(step.get('args', {}))}{RESET}")
            seen_plan = True
        for step in job.get("steps", []):
            sid, status = step["step_id"], step["status"]
            if step_status.get(sid) != status:
                step_status[sid] = status
                color = STEP_COLOR.get(status, "")
                line = (f"  {color}{STEP_GLYPH.get(status, '?')} step {sid} "
                        f"{step['tool']} — {status}{RESET}")
                if step.get("error"):
                    line += f"  {RED}{step['error']}{RESET}"
                say(line)
        if job["status"] in ("complete", "failed"):
            answer = job.get("answer") or ""
            if answer:
                preview = " ".join(answer.split())[:180]
                say(f"  {GREEN}ANSWER ({len(answer)} chars):{RESET} {preview}…")
            color = GREEN if job["status"] == "complete" else RED
            say(f"  {color}{BOLD}DONE — {job['status']}{RESET}")
            say(f"{DIM}waiting for next request…{RESET}")
            say()
            return
        time.sleep(0.3)


def agent_mode():
    tokens = load_tokens()
    poll_token = tokens["analyst-full"]
    banner_roles(tokens)
    say(f"{DIM}waiting for requests…{RESET}\n")
    seen_jobs = set()
    for rec in tail("integration-api"):
        if rec.get("message") != "job created":
            continue
        # logging_setup flattens extra["ctx"] into top-level fields
        job_id = rec.get("job_id") or rec.get("ctx", {}).get("job_id")
        user = rec.get("user_sub") or rec.get("ctx", {}).get("user_sub")
        if not job_id or job_id in seen_jobs:
            continue
        seen_jobs.add(job_id)
        try:
            job = http_json(f"{API}/v1/jobs/{job_id}", poll_token)
            query = job.get("query", "?")
            turns = len(job.get("messages", [])) or 1
        except Exception:
            query, turns = "?", 1
        say(f"{CYAN}{BOLD}▶ REQUEST{RESET} {CYAN}from {user} "
            f"(turn {turns}) — job {job_id[:8]}{RESET}")
        say(f"  {CYAN}query:{RESET} {query}")
        try:
            names = tools_list(tokens[user])
            wdp = sum(1 for n in names if "wdp" in n)
            note = "" if wdp else f" {YELLOW}— WDP tools withheld{RESET}"
            say(f"  {DIM}tools/list for this session: {len(names)} tools{note}{RESET}")
        except Exception:
            pass
        watch_job(job_id, poll_token)


# --- audit mode -----------------------------------------------------------------


def audit_mode():
    say(f"{BOLD}{MAGENTA}══ MCP SERVER — AUDIT STREAM (every tools/call, separate container) ══{RESET}")
    say(f"{DIM}time      user           tool                      args → outcome{RESET}\n")
    for rec in tail("mcp-server"):
        if not rec.get("audit"):
            continue
        outcome = rec.get("outcome", "?")
        color = OUTCOME_COLOR.get(outcome, "")
        clock = (rec.get("timestamp", ""))[11:19]
        rows = rec.get("result_count")
        rows_txt = f"{rows} rows" if rows is not None else "-"
        say(f"{DIM}{clock}{RESET}  {rec.get('sub', '?'):<13}  "
            f"{BOLD}{rec.get('tool', '?'):<24}{RESET} "
            f"{DIM}{compact(rec.get('args', {}), 60)}{RESET} "
            f"→ {color}{BOLD}{outcome}{RESET} {DIM}({rows_txt}, "
            f"{rec.get('duration_ms', '?')}ms){RESET}")


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else ""
    if mode == "agent":
        agent_mode()
    elif mode == "audit":
        audit_mode()
    else:
        sys.exit("usage: python3 scripts/demo_tap.py agent|audit")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
